name: Ruff Lint

on:
  push:
    branches: [ main, master, dev, develop, stage* ]
  pull_request:

concurrency:
  group: ruff-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps (no build)
        run: poetry install --no-root --only dev
        # pip alternative:
        # run: pip install -r requirements-dev.txt

      - name: Ruff (lint)
        run: poetry run ruff check .
        # pip alt: ruff check .
