name: Format Check (black + isort)

on:
  push:
    branches: [ main, master, dev, develop, stage* ]
  pull_request:

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps (no build)
        run: poetry install --no-root --only dev

      - name: isort (check-only)
        run: poetry run isort . --check-only --diff

      - name: black (check)
        run: poetry run black . --check --diff
