name: Tests & Lint (uv)

on:
  push:
    branches: [ main, master, dev, develop, stage* ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment (install Python & dependencies)
        run: uv sync --all-extras --dev

      - name: Ruff Lint & Format Check
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Run pytest
        run: uv run pytest -v --maxfail=1 --disable-warnings
